### ISSUE TITLE
Passwords

### ISSUE THREAD

**Issue by jclyons** [wesleyan/chef-cookbooks#1]
Mountain Lion uses SHA 512 DKBF2 password hashes. The directory adapter for Mac OS X needs to figure out how to interface with this. Submitted a bug http://tickets.opscode.com/browse/CHEF-3523 to Opscode.

**Comment by rchristensen** [comment]
CHEF-3523 was closed for being a dupe of http://tickets.opscode.com/browse/CHEF-2813 - both tickets contain reference information on how puppet solved this issue. Hopefully opscode will resolve this, but in the interim we can manage account passwords manually.  If we get to a point where we have nothing else to work on I think I'll have us solve this ourselves and contribute back to chef.

**Comment by rchristensen** [comment]
Max has worked around password changes use expect and the passwd cmd, but this doesn't solve dynamic account creation which is the ultimate goal
