### ISSUE TITLE
CFPrefsD overwrites com.apple.dock.plist

### ISSUE THREAD

**Issue by jclyons** [wesleyan/chef-cookbooks#2]
Modifying the standard com.apple.dock.plist by placing a com.apple.dock.plist into ~/Library/Preferences of the default user skeleton doesn't stick, since CFPrefsd keeps writing over the com.apple.dock.plist contained in the new user's directory with the default one.

**Comment by rchristensen** [comment]
Didn't we resolve this?

**Comment by mdietz94** [comment]
Since the Dock has been updating, I think this problem should have been closed months ago.
