### ISSUE TITLE
Suppress XythosDrive from automatically starting up on login

### ISSUE THREAD

**Issue by rchristensen** [wesleyan/chef-cookbooks#61]
It also seems to hang on launch, but it's inconsistent behavior and not related to cookbooks.. still need to investigate though.

**Comment by mdietz94** [comment]
I've only noticed this behavior on the Administrator account, which does not get configured by Chef

**Comment by rchristensen** [comment]
Saw it on labuser today, did not try AD accounts.. I'll double check.

**Comment by mdietz94** [comment]
Behavior does not apply to actual (AD) accounts
