### ISSUE TITLE
Automated deployment changelog on user desktop

### ISSUE THREAD

**Issue by rchristensen** [wesleyan/chef-cookbooks#85]
We should figure out a way to generate a deployment changelog either from chef-cookbook changelog updates or github commits and automatically publish it to user's desktops.

This should maybe be another issue, but we should resurrect desktop_picture to overlay and show the last time chef was successfully ran as well.. both of these go a long way to helping techs and users know when a machine was last updated and with what

**Comment by mdietz94** [comment]
I could make a success handler that does it like emailer does now.  Might be tricky to find out the current revision though.
